### ISSUE TITLE
What about npm binaries?

### ISSUE THREAD

**Issue by grigorii-horos** [artifact-project/npmy#6]
Now npmy doesn't add files in node_modules/.bin directory. Will be nice if you add ability to link binaries.

**Comment by RubaXa** [comment]
Are you sure?

For example right now (with `verbose`):
![image](https://user-images.githubusercontent.com/1109562/33737282-9c16ade8-dba6-11e7-9d71-2b4785c4f060.png)

and `ls -al`
![image](https://user-images.githubusercontent.com/1109562/33737417-140c3cb4-dba7-11e7-8ad1-067c70608d22.png)

**Comment by RubaXa** [comment]
I found the problem and fix it: https://github.com/artifact-project/npmy/commit/a38dfcc096898d388002535cb6722b542a59cb65

**Comment by RubaXa** [comment]
@horosgrisa Is everything fine?

**Comment by grigorii-horos** [comment]
Еще до того как был исправлен баг, я уже перестал использовать npmy, поэтому не могу проверить. Но штука хорошая, и в других проектах я ее точно буду использовать.
